# svm using linear kernel

In [179]:
import  numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('main.csv')
df

AverageShortestPathLength  BetweennessCentrality  ClosenessCentrality  \
0                    8.640046               0.036598             0.115740   
1                    6.699074               0.023132             0.149274   
2                    6.625000               0.028912             0.150943   
3                    7.079861               0.022103             0.141246   
4                    7.114583               0.015466             0.140556   
5                    7.109954               0.014929             0.140648   
6                    7.171296               0.024206             0.139445   
7                    7.876157               0.055609             0.126965   
8                    7.104167               0.107686             0.140762   
9                    7.516204               0.033078             0.133046   
10                   6.612269               0.061830             0.151234   
11                   6.863426               0.013896             0.145700   
12                   6.134259               0.210707             0.163019   
13                   6.983796               0.017078             0.143189   
14                   7.601852               0.043523             0.131547   
15                   6.135417               0.105439             0.162988   
16                   6.135417               0.105655             0.162988   
17                   6.594907               0.055045             0.151632   
18                   6.094907               0.130184             0.164071   
19                   6.047454               0.092069             0.165359   
20                   6.630787               0.020072             0.150812   
21                   6.733796               0.049319             0.148505   
22                   6.498843               0.070906             0.153874   
23                   1.975000               0.730769             0.506329   
24                   5.608796               0.262476             0.178291   
25                   5.858796               0.244066             0.170684   
26                   8.285880               0.039943             0.120687   
27                   7.723380               0.034370             0.129477   
28                   7.724537               0.034315             0.129458   
29                   8.045139               0.043523             0.124299   
30                   8.792824               0.058315             0.113729   
31                   9.737269               0.020708             0.102698   
32                   9.737269               0.022979             0.102698   
33                   8.796296               0.051280             0.113684   
34                   6.137731               0.075748             0.162927   
35                   5.540509               0.238164             0.180489   
36                   5.615741               0.245208             0.178071   
37                   3.194245               0.169965             0.313063   
38                   2.956835               0.245296             0.338200   
39                   3.467626               0.098989             0.288382   
40                   1.000000               1.000000             1.000000   
41                   2.834532               0.324184             0.352792   
42                   3.453237               0.140678             0.289583   
43                   3.503597               0.104110             0.285421   
44                   6.983796               0.029030             0.143189   
45                   8.233796               0.025126             0.121451   
46                   1.975000               0.730769             0.506329   
47                   1.000000               1.000000             1.000000   
48                   1.000000               1.000000             1.000000   
49                   8.285880               0.038544             0.120687   
50                   7.283565               0.064503             0.137295   


In [180]:
# X -> features, y -> label
#here we will not use gender and user id
#on the basis of age and estimated salary we will decide the person will purchase the product or not
x=df.iloc[:,[0]]# that's why in x we have 0th no column 
y=df.iloc[:,4]#and in y we have column no 4 that we will predict means dependent variable
  


In [181]:
print(x.head())
#.head() is used to predict first five values

   AverageShortestPathLength
0                   8.640046
1                   6.699074
2                   6.625000
3                   7.079861
4                   7.114583


In [182]:
print(y.head())

0    21
1    20
2    21
3    23
4    22
Name: Degree, dtype: int64


In [183]:
#now devide or split the data for training and testing the set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)
#means 25% data will consider as test data and remaining data will consider as tarining data

In [184]:
#check the shape of traing and testing data
print(x_train.shape)
print(x_test.shape)
#means we will train our model in the basis of first 300 row of that 2 colummn age and estimated salary
#and we will test  our model in the basis of last remaining 100 row of that 2 colummn age and estimated salary

(39, 1)
(14, 1)


In [185]:
#now scale or feature or preprocessing the data using standard sccaler we can use minmax scaler too for scalling the data
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.fit_transform(x_test)

In [186]:
#apply svm algo for classification
#by finding the right hyperplane that classifies the datapoint in the graph
from sklearn.svm import SVC
#in svm we have many kernal like linear,sigmoid,polynomial,rbf we usde here linear
classifier = SVC(kernel ='linear',random_state=0)
classifier.fit(x_train,y_train)#here we train pour alogorithm



SVC(kernel='linear', random_state=0)

In [187]:
y_pred=classifier.predict(x_test)
y_pred
#here we will have 100 data means y value for 100 x test values
#these are the predicted value in boolean format

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
      dtype=int64)

In [188]:
 # Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred )*100,"%")
print("F1 score:",metrics.f1_score(y_test, y_pred, average='weighted')*100,"%")
print("recall:",metrics.recall_score(y_test, y_pred, average='weighted')*100,"%")
print("precision:",metrics.precision_score(y_test, y_pred, average='micro')*100,"%")

Accuracy: 42.857142857142854 %
F1 score: 25.71428571428571 %
recall: 42.857142857142854 %
precision: 42.857142857142854 %


# svm with rbf kernel

In [189]:
#now devide or split the data for training and testing the set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.50,random_state=0)
#means 25% data will consider as test data and remaining data will consider as tarining data

In [190]:
#now scale or feature or preprocessing the data using standard sccaler we can use minmax scaler too for scalling the data
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.fit_transform(x_test)

In [191]:
#apply svm algo for classification
#by finding the right hyperplane that classifies the datapoint in the graph
from sklearn.svm import SVC
#in svm we have many kernal like linear,sigmoid,polynomial,rbf we usde here rbf
classifier = SVC(kernel ='rbf')
classifier.fit(x_train,y_train)#here we train pour alogorithm


SVC()

In [192]:
y_pred=classifier.predict(x_test)
y_pred
#here we will have 100 data means y value for 100 x test values
#these are the predicted value in boolean format

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20], dtype=int64)

In [193]:
 # Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred )*100,"%")
print("F1 score:",metrics.f1_score(y_test, y_pred, average='weighted')*100,"%")
print("recall:",metrics.recall_score(y_test, y_pred, average='macro')*100,"%")
print("precision:",metrics.precision_score(y_test, y_pred, average='micro')*100,"%")

Accuracy: 62.96296296296296 %
F1 score: 48.65319865319865 %
recall: 62.96296296296296 %
precision: 62.96296296296296 %


# svm using polynomial kernel

In [230]:
#now devide or split the data for training and testing the set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)
#means 25% data will consider as test data and remaining data will consider as tarining data

In [231]:
#now scale or feature or preprocessing the data using standard sccaler we can use minmax scaler too for scalling the data
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.fit_transform(x_test)

In [232]:
#apply svm algo for classification
#by finding the right hyperplane that classifies the datapoint in the graph
from sklearn.svm import SVC
#in svm we have many kernal like linear,sigmoid,polynomial,rbf we usde here rbf
ddd = SVC(kernel ='poly',degree=4)
ddd.fit(x_train,y_train)#here we train pour alogorithm



SVC(degree=4, kernel='poly')

In [233]:
y_pred=ddd.predict(x_test)
y_pred
#here we will have 100 data means y value for 100 x test values
#these are the predicted value in boolean format

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
      dtype=int64)

In [241]:
 # Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred )*100,"%")
print("F1 score:",metrics.f1_score(y_test, y_pred, average='weighted')*100,"%")
print("recall:",metrics.recall_score(y_test, y_pred, average='macro')*100,"%")
print("precision:",metrics.precision_score(y_test, y_pred, average='micro')*100,"%")

Accuracy: 42.857142857142854 %
F1 score: 25.71428571428571 %
recall: 25.0 %
precision: 42.857142857142854 %


# linear regression

In [203]:
# Splitting the dataset into training and testing set (80/20)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 28)
# Initializing the Linear Regression model
from sklearn.linear_model import LinearRegression
model = LinearRegression()
# Fitting the Multiple Linear Regression model to the data
model.fit(x_train, y_train)

y_pred = model.predict(x_test)
y_pred

array([20.53407156, 21.07980787, 20.52038429, 20.52757888, 20.05180651,
       20.12924907, 20.08780094, 20.60794776, 20.85975857, 20.64409621,
       20.7744763 ])

In [216]:
from sklearn.metrics import r2_score
Accuracy=r2_score(y_test,y_pred)*100
print(" Accuracy of the model is %.2f" %Accuracy,"%")

 Accuracy of the model is 32.02 %


# Decision tree

In [129]:
from sklearn.tree import DecisionTreeClassifier
x=df.iloc[:,[0]]# that's why in x we have 0th no column 
y=df.iloc[:,4]#and in y we have column no 4 that we will predict means dependent variable
  
    #now devide or split the data for training and testing the set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=28)

dt = DecisionTreeClassifier()
dt.fit(x_train,y_train)
y_pred2 = dt.predict(x_test)
print(y_pred2)


[20 22 20 20 20 20 20 20 20 20 20]


In [226]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred2 )*100,"%")
print("F1 score:",metrics.f1_score(y_test, y_pred2, average='macro')*100,"%")
print("recall:",metrics.recall_score(y_test, y_pred2, average='macro')*100,"%")
print("precision:",metrics.precision_score(y_test, y_pred2, average='micro')*100,"%")

Accuracy: 63.63636363636363 %
F1 score: 47.222222222222214 %
recall: 50.0 %
precision: 63.63636363636363 %
